### ISSUE TITLE
样式加载

### ISSUE THREAD

**Issue by nhyilin** [616620131/Multiverse-page-typecho#1]
样式第一次加载不出来，要刷新一下才可以，要加cdn才可以嘛

**Comment by zzd** [comment]
什么意思？具体是哪个文件无法加载吗

**Comment by zzd** [comment]
No response for more than a week, close the issue.

**Comment by zzfiu** [comment]
好像是开启了Pjax的原因，不能加载。刷新一下就可以了。有办法解决吗

**Comment by zzd** [comment]
你应该需要pjax预加载，这是pjax的问题。
