### ISSUE TITLE
希望作者可以添加播放视频的样式

### ISSUE THREAD

**Issue by Easione** [616620131/Multiverse-page-typecho#12]
RT，想要放些视频但是不太会代码，希望作者有空的时候可以考虑添加一下呀 谢谢

**Comment by Easione** [comment]
我在手机端打开网页可以播放视频，但是电脑端Google浏览器播放不了视频，我再check一下 QAQ

**Comment by zzd** [comment]
相册页面不支持放视频，没有引入视频相关组件
