### ISSUE TITLE
增加才尺寸较大的图片点击图片预览展示有些问题

### ISSUE THREAD

**Issue by anwen-anyi** [616620131/Multiverse-page-typecho#13]
### RT
添加一些尺寸为 1668x2500，图片太大了PC预览的时候不会
PC/web端口不正常:https://cdn.jsdelivr.net/gh/anwen-anyi/imgAnwen/images/PCimages.png
APP端正常:https://cdn.jsdelivr.net/gh/anwen-anyi/imgAnwen/images/imagesError2.png
 
作者大大这种能修复吗?

**Comment by zzd** [comment]
没看出哪里异常了
