### ISSUE TITLE
Multiverse风格相册点击单个相片时，只有关闭的X，无查看左右相片的< >按钮

### ISSUE THREAD

**Issue by coderZoe** [616620131/Multiverse-page-typecho#14]
如：
![image](https://user-images.githubusercontent.com/55009317/173192123-c7e75dd3-c63b-45c4-a49d-9e24968dac3f.png)

**Comment by zzd** [comment]
提供一下链接。

**Comment by coderZoe** [comment]
http://www.coderzoe.com/image.html

**Comment by coderZoe** [comment]
> 提供一下链接。

http://www.coderzoe.com/image.html

**Comment by zzd** [comment]
是因为jsdelivr中国大陆区域服务挂掉了。
https://github.com/zzd/photo-page-for-typecho/blob/b49ef21510b7698fb20ebb0b5ee64ef1e01508c8/Multiverse.php#L18
这句改为`echo "https://fastly.jsdelivr.net/gh/zzd/photo-page-for-typecho@master";`

**Comment by coderZoe** [comment]
> 

可以了，非常感谢
