### ISSUE TITLE
图片不显示，一片黑，只能看到缩略图，大图看不到

### ISSUE THREAD

**Issue by 0xabz** [616620131/Multiverse-page-typecho#18]
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/47265341/226179319-69b7685b-7c68-4163-b548-04c04c1bada5.png">

**Comment by 0xabz** [comment]
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/47265341/226179441-e2ce8613-f929-4434-ad03-59cc9b9e3acb.png">

然后Multiverse这种情况显示的时候就看不见，只有点进去才能看到
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/47265341/226179690-e447370c-2a20-4860-9edd-f23ed686a009.png">

**Comment by zzd** [comment]
请提供你的链接

**Comment by A563185000** [comment]
http://47.92.233.108:9527/photo.html

**Comment by A563185000** [comment]
> 请提供你的链接

http://47.92.233.108:9527/photo.html

**Comment by 0xabz** [comment]
请问如何解决

**Comment by zzd** [comment]
图片链接中请不要带括号

**Comment by 0xabz** [comment]
> 图片链接中请不要带括号

感谢！！！解决了
