### ISSUE TITLE
好奇问一下和time主题有啥联系不

### ISSUE THREAD

**Issue by FatDoge** [616620131/Multiverse-page-typecho#2]
status.fatdoge.cn 这个相册主题和那个模板一模一样 哪个先哪个后呢

**Comment by FatDoge** [comment]
哦好像都是用的这个模板https://html5up.net/multiverse

**Comment by zzd** [comment]
你好，没有联系。都是用的HTML5UP的开源模板适配了一下，我这个是单页模板，你说那个应该是主题。具体你可以仔细阅读[README](https://github.com/616620131/photo-page-for-typecho/blob/master/README.md)。

**Comment by FatDoge** [comment]
好的大佬
