### ISSUE TITLE
Lens风格能否展示图片全尺寸

### ISSUE THREAD

**Issue by gaoxianglyx** [616620131/Multiverse-page-typecho#8]
很喜欢Lens风格
但是大部分图片因为比例问题无法展示完整图片，
目前正对非默认比例的图片是不展示多余比例部分，能否修改为缩放至展示完整图片？
或者给出接口来自己控制

感谢

**Comment by aotxland** [comment]
遇到了同样的问题，我是使用七牛直接把图片剪成能完全展示的尺寸，希望能提供缩放功能

**Comment by chenbaker** [comment]
遇到同样的问题，希望有新版本

**Comment by zzd** [comment]
模板的代码没有这方面的适应能力，比例不对的照片应该如何展示，也是一个问题。

**Comment by zzd** [comment]
[Update main.css](https://github.com/zzd/photo-page-for-typecho/commit/d007547513cb551146c4413dd24450c6525810dc) 已解决
